'use client'
import { createContext, useContext, useEffect, useState, ReactNode } from 'react'

export type Lang = 'uk' | 'en'

const dict: Record<Lang, Record<string, string>> = {
  uk: {
    topbar: 'Безкоштовна доставка · Ручна робота на замовлення',
    nav_catalog: 'Каталог',
    nav_about: 'Про нас',
    nav_reviews: 'Відгуки',
    nav_contacts: 'Контакти',
    aria_menu: 'Меню',
    aria_account: 'Кабінет',
    aria_favorites: 'Вподобані',
    aria_cart: 'Кошик',
    hero_eyebrow: 'Екодизайн · Ручна робота',
    hero_cta_products: 'Переглянути вироби',
    hero_cta_contact: 'Зв’язатись',
    svc1_t: 'Безкоштовна доставка',
    svc1_d: 'По всій Україні при замовленні від 1200 грн.',
    svc2_t: 'Обмін та повернення',
    svc2_d: '14 днів на обмін або повернення виробу.',
    svc3_t: 'Індивідуальне замовлення',
    svc3_d: 'Виготовимо столик під ваш інтер’єр.',
    about_eyebrow: 'Мінімалізм і турбота про планету',
    about_title: 'Чому обирають нас',
    about1_t: 'Друге життя м’ячів',
    about1_d: 'Кожен столик — це десятки відпрацьованих тенісних м’ячів, що знайшли нове застосування.',
    about2_t: 'Скляна стільниця',
    about2_d: 'Загартоване скло робить поверхню міцною, легкою в догляді та візуально повітряною.',
    about3_t: 'Ручна робота',
    about3_d: 'Ми збираємо кожен виріб вручну — з увагою до деталей і геометрії.',
    badge_recycled: '♥ 100% перероблені матеріали',
    reviews_eyebrow: 'Що кажуть покупці',
    reviews_title: 'Відгуки',
    rev1: 'Столик став акцентом вітальні. Виглядає навіть краще, ніж на фото!',
    rev2: 'Якісна збірка, скло приємне на дотик. І сама ідея переробки — супер.',
    rev3: 'Замовляла в подарунок — усі в захваті. Доставили швидко.',
    cat_eyebrow: 'Наші вироби',
    cat_title: 'Каталог',
    cat_sub: 'Столики та стільці зі скляною стільницею — обирайте під свій інтерʼєр.',
    f_category: 'Категорія:',
    f_all: 'Усі',
    f_availability: 'Наявність:',
    f_instock: 'В наявності',
    f_outstock: 'Немає',
    f_sort: 'Сортування:',
    f_sort_default: 'За замовчуванням',
    f_sort_cheap: 'Дешевші спершу',
    f_sort_exp: 'Дорожчі спершу',
    f_search: 'Пошук:',
    f_price: 'Ціна, ₴:',
    f_sale_only: 'Лише акції',
    ph_product: 'Назва товару...',
    ph_from: 'від',
    ph_to: 'до',
    loading: 'Завантаження...',
    nothing_found: 'Нічого не знайдено',
    found: 'Знайдено',
    no_photo: 'нема фото',
    lbl_size: 'Розмір:',
    lbl_color: 'Колір:',
    add_to_cart: 'В кошик',
    fav_remove: 'Видалити з вподобаного',
    fav_add: 'Додати в вподобане',
    cart_title: 'Кошик',
    cart_empty: 'Кошик порожній',
    remove: 'Видалити',
    total: 'Разом:',
    checkout: 'Оформити замовлення',
    pay_cod: 'Наложений платіж',
    pay_card: 'Передоплата на картку',
    err_name_phone: 'Вкажіть імʼя та телефон',
    err: 'Помилка',
    order_thanks: 'Дякуємо! Замовлення прийнято.',
    ph_name_req: 'Імʼя *',
    ph_phone_req: 'Телефон *',
    ph_city: 'Місто / Відділення',
    ph_comment: 'Коментар',
    sending: 'Надсилаємо...',
    confirm_order: 'Підтвердити замовлення',
    fav_title: 'Вподобані',
    fav_empty: 'Список вподобаного порожній',
    contacts_eyebrow: 'Звʼяжіться з нами',
    contacts_title: 'Контакти',
    contacts_sub: 'Маєте питання про виріб, доставку чи індивідуальне замовлення? Напишіть — відповімо якнайшвидше.',
    contacts_thanks: 'Дякуємо! Ми звʼяжемось з вами.',
    c_name: 'Імʼя',
    c_phone: 'Телефон',
    c_message: 'Повідомлення',
    c_send: 'Надіслати',
  },
  en: {
    topbar: 'Free delivery · Handmade to order',
    nav_catalog: 'Catalog',
    nav_about: 'About',
    nav_reviews: 'Reviews',
    nav_contacts: 'Contacts',
    aria_menu: 'Menu',
    aria_account: 'Account',
    aria_favorites: 'Favorites',
    aria_cart: 'Cart',
    hero_eyebrow: 'Eco design · Handmade',
    hero_cta_products: 'View products',
    hero_cta_contact: 'Get in touch',
    svc1_t: 'Free delivery',
    svc1_d: 'Across Ukraine on orders over 1200 UAH.',
    svc2_t: 'Exchange & returns',
    svc2_d: '14 days to exchange or return an item.',
    svc3_t: 'Custom order',
    svc3_d: 'We’ll craft a table to match your interior.',
    about_eyebrow: 'Minimalism and care for the planet',
    about_title: 'Why choose us',
    about1_t: 'A second life for tennis balls',
    about1_d: 'Each table is made of dozens of used tennis balls given a new purpose.',
    about2_t: 'Glass tabletop',
    about2_d: 'Tempered glass makes the surface durable, easy to clean and visually light.',
    about3_t: 'Handmade',
    about3_d: 'We assemble every piece by hand — with attention to detail and geometry.',
    badge_recycled: '♥ 100% recycled materials',
    reviews_eyebrow: 'What customers say',
    reviews_title: 'Reviews',
    rev1: 'The table became the accent of our living room. Looks even better than in the photos!',
    rev2: 'Great build quality, the glass feels pleasant. And the recycling idea itself is superb.',
    rev3: 'Ordered it as a gift — everyone loved it. Delivered quickly.',
    cat_eyebrow: 'Our products',
    cat_title: 'Catalog',
    cat_sub: 'Tables and chairs with a glass top — choose to match your interior.',
    f_category: 'Category:',
    f_all: 'All',
    f_availability: 'Availability:',
    f_instock: 'In stock',
    f_outstock: 'Out of stock',
    f_sort: 'Sorting:',
    f_sort_default: 'Default',
    f_sort_cheap: 'Cheapest first',
    f_sort_exp: 'Most expensive first',
    f_search: 'Search:',
    f_price: 'Price, ₴:',
    f_sale_only: 'On sale only',
    ph_product: 'Product name...',
    ph_from: 'from',
    ph_to: 'to',
    loading: 'Loading...',
    nothing_found: 'Nothing found',
    found: 'Found',
    no_photo: 'no photo',
    lbl_size: 'Size:',
    lbl_color: 'Color:',
    add_to_cart: 'Add to cart',
    fav_remove: 'Remove from favorites',
    fav_add: 'Add to favorites',
    cart_title: 'Cart',
    cart_empty: 'Your cart is empty',
    remove: 'Remove',
    total: 'Total:',
    checkout: 'Checkout',
    pay_cod: 'Cash on delivery',
    pay_card: 'Card prepayment',
    err_name_phone: 'Please enter your name and phone',
    err: 'Error',
    order_thanks: 'Thank you! Your order has been received.',
    ph_name_req: 'Name *',
    ph_phone_req: 'Phone *',
    ph_city: 'City / Post office',
    ph_comment: 'Comment',
    sending: 'Sending...',
    confirm_order: 'Confirm order',
    fav_title: 'Favorites',
    fav_empty: 'Your favorites list is empty',
    contacts_eyebrow: 'Get in touch',
    contacts_title: 'Contacts',
    contacts_sub: 'Have a question about a product, delivery or a custom order? Write to us — we’ll reply as soon as possible.',
    contacts_thanks: 'Thank you! We’ll get in touch with you.',
    c_name: 'Name',
    c_phone: 'Phone',
    c_message: 'Message',
    c_send: 'Send',
  },
}

type LangCtx = {
  lang: Lang
  setLang: (l: Lang) => void
  t: (key: string) => string
}

const Ctx = createContext<LangCtx | null>(null)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>('uk')
  useEffect(() => {
    try {
      const saved = localStorage.getItem('lang') as Lang | null
      if (saved === 'uk' || saved === 'en') setLangState(saved)
    } catch {}
  }, [])
  const setLang = (l: Lang) => {
    setLangState(l)
    try { localStorage.setItem('lang', l) } catch {}
  }
  const t = (key: string) => (dict[lang] && dict[lang][key]) || (dict.uk[key]) || key
  return <Ctx.Provider value={{ lang, setLang, t }}>{children}</Ctx.Provider>
}

export function useLang() {
  const c = useContext(Ctx)
  if (!c) throw new Error('useLang must be used within LanguageProvider')
  return c
}
